version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
    restart: unless-stopped

  frontend:
    build: ./
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
